### ISSUE TITLE
Allowing absolute and relative path for copy-from-controller

### ISSUE THREAD

**Issue by kameshsampath** [rhtconsulting/jboss_eap#36]
Right now the `copy-from-controller` setting for `transfer_method` looks for the archive in the current directory  of the controller machine from where the ansible is run, and hence the task 
```
- name: Copy JBoss EAP
  copy:
    src: "{{ jboss_eap_artifact_name }}"
    dest: "{{ jboss_eap_artifact_dl_dest }}"
  tags:
    - jboss_eap
  when: transfer_method == 'copy-from-controller' and jboss_eap_exists.stat.exists == false
```
fails if we give a path like `/mypath/softwares/jboss-eap-6.4.zip`
